### ISSUE TITLE
Should variable "index" start from zero?

### ISSUE THREAD

**Issue by andreastedile** [giuspek/Formal-Methods-Lab#3]
In lab 2's examples, I see that the global variable "index" at the top each script is initialized with the value 1.
If I'm not mistaken, this variable should represent the number of variables that have been defined, thus should be initialized with value 0.

My fix proposals:

```
# The top of the scripts
index = 0   # 0, not one!
```

Or:

```
# if we use "index", we are counting a variable in excess
# thus, we should use "index - 1" 
output_file.write("c Add this problem line: p cnf {} {}".format(index - 1, n_clauses))
```

What do you think?

**Comment by giuspek** [comment]
The choice behind "index = 1" is necessary to avoid problems while mapping generic variables into their indexed equivalent in DIMACS format, since 0 cannot be used as a variable (it can only be used as a limiter among clauses). On the other hand, you are right about updating the problem line, otherwise, we would consider an additional useless variable into our problem. I'll update the code so that it reflects this discussion.

PS: If we do not modify the last line, the SAT solver simply creates an additional variable without using it; the solution obtained is still valid, but of course it is better to fix it for the sake of correctness.
